export enum EErrors {
	TEST = "TEST",
	INVALID_DATA_SERVICE = "INVALID_DATA_SERVICE",
	INVALID_LOGIN = "INVALID_LOGIN",
	VALIDATE_FAIL = "VALIDATE_FAIL",
	INVALID_OBJ_SCHEMA = "INVALID_OBJ_SCHEMA",
	INVALID_REQUEST = "INVALID_REQUEST",
	INVALID_SQL_RESULT = "INVALID_SQL_RESULT",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	CLASS_NOT_FOUND = "CLASS_NOT_FOUND",
	USER_CLASS_NOT_FOUND = "USER_CLASS_NOT_FOUND",
	INVALID_CLASS_NAME = "INVALID_CLASS_NAME",
	ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND",
	CLASS_CONTENT_NOT_FOUND = "CLASS_CONTENT_NOT_FOUND",
	COVER_NOT_FOUND = "COVER_NOT_FOUND",
	USER_GROUP_NOT_FOUND = "USER_GROUP_NOT_FOUND",
	GROUP_USER_ASSOCIATE_FAIL = "GROUP_USER_ASSOCIATE_FAIL",
	USER_ORGANIZATION_NOT_FOUND = "USER_ORGANIZATION_NOT_FOUND",
	ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
	ORGANIZATION_ACCESS_DENIED = "ORGANIZATION_ACCESS_DENIED",
	INVALID_CONTENT_NAME = "INVALID_CONTENT_NAME",
	INVALID_EMBED_CONTENT = "INVALID_EMBED_CONTENT",
	INVALID_GRADE_VALUE = "INVALID_GRADE_VALUE",
	INVALID_GRADE_TYPE = "INVALID_GRADE_TYPE",
	INVALID_USER_CLASS_PROGRESS_TYPE = "INVALID_USER_CLASS_PROGRESS_TYPE",
	ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND",
	INVALID_DATA = "INVALID_DATA",

	ACCESS_DENIED = 'ACCESS_DENIED',
	NO_TOKEN = 'NO_TOKEN',
	INVALID_TOKEN = 'INVALID_TOKEN',

	//CREATE USER
	INVALID_NAME = "INVALID_NAME",
	INVALID_USERNAME = "INVALID_USERNAME",
	INVALID_EMAIL = "INVALID_EMAIL",
	INVALID_PASSWORD = "INVALID_PASSWORD",
	INVALID_REPEATED_PASSWORD = "INVALID_REPEATED_PASSWORD",
	CREATE_USER_FAIL = "CREATE_USER_FAIL",

	// CREATE PRODUCT
	INVALID_CATEGORY = "INVALID_CATEGORY",
	INVALID_PHOTO = "INVALID_PHOTO",
	CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL",

	// EDIT PRODUCT
	EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL",

	// REMOVE PRODUCT
	REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL",

	// CREATE CATEGORY
	CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL",

	// EDIT CATEGORY
	EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL",

	// REMOVE CATEGORY
	REMOVE_CATEGORY_FAIL = "REMOVE_CATEGORY_FAIL",


	// CREATE BANNER
	CREATE_BANNER_FAIL = "CREATE_BANNER_FAIL",
	INVALID_LINK = "INVALID_LINK",

	// EDIT BANNER
	EDIT_BANNER_FAIL = "EDIT_BANNER_FAIL",

	// REMOVE BANNER
	REMOVE_BANNER_FAIL = "REMOVE_BANNER_FAIL",
};